no_default_gcc script: reword error message and print it after, not before, the command that was attempted
git-svn-id: https://svn.macports.org/repository/macports/users/ryandesign@52005 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/no_default_gcc/cc b/no_default_gcc/cc
--- a/no_default_gcc/cc
+++ b/no_default_gcc/cc
@@ -14,7 +14,7 @@ case "$PROG" in
 		;;
 esac
 
-echo "Error: You tried to use $PROG instead of /usr/bin/$NEWPROG-*:" 1>&2
 echo "$PROG $@" 1>&2
+echo "$PROG: Error: You should be using /usr/bin/$NEWPROG-*:" 1>&2
 echo "See http://trac.macports.org/wiki/UsingTheRightCompiler" 1>&2
 exit 1
