no_default_gcc script: show the name of the configure var that should be used
git-svn-id: https://svn.macports.org/repository/macports/users/ryandesign@52202 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/no_default_gcc/cc b/no_default_gcc/cc
--- a/no_default_gcc/cc
+++ b/no_default_gcc/cc
@@ -3,18 +3,18 @@
 
 PROG=$(basename "$0")
 case "$PROG" in
-	cc)
-		NEWPROG=gcc
+	gcc)
+		VAR=cc
 		;;
-	c++)
-		NEWPROG=g++
+	c++|g++)
+		VAR=cxx
 		;;
 	*)
-		NEWPROG="$PROG"
+		VAR="$PROG"
 		;;
 esac
 
 echo "$PROG $@" 1>&2
-echo "$PROG: Error: You should be using /usr/bin/$NEWPROG-*:" 1>&2
+echo "$PROG: Error: You should be using \${configure.$VAR}" 1>&2
 echo "See http://trac.macports.org/wiki/UsingTheRightCompiler" 1>&2
 exit 1
